[package]
name = "quick-pose"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
gtk = {version = "0.4.6", package = "gtk4"}
relm4 = { version = "0.4", features = ["macros"] }
relm4-components = "0.4"